---
title: "EDA"
author: "Stephan"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 300, message = FALSE, warning = FALSE)
```

## Daily exploration of ICU Bed Capacity

Data Source: https://edoc.rki.de/handle/176904/7011

```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(purrr)
library(lubridate)
library(patchwork)
library(showtext)
library(stringr)
font_add_google("Roboto Condensed", "conde")
showtext_auto()
theme_set(theme_light(base_family = "conde", base_size = 28))
heute <- format(Sys.Date(), "%b %d, %Y")


icu_files <- list.files(path = "data_raw/", pattern = "csv", full.names = TRUE)
data_raw <- map_df(icu_files, function (x) read_csv(x) %>% 
                     mutate(date = x,
                            date = str_extract_all(date, "[0-9]{4}-[0-9]{2}-[0-9]{2}"),
                            date = ymd(date))
)
```


```{r eval=FALSE}
data_raw %>% 
  glimpse()

data_raw %>% 
  naniar::vis_miss(warn_large_data = FALSE)
```


```{r}
data_clean <- data_raw %>% 
  mutate(gemeindeschluessel = if_else(is.na(gemeindeschluessel), kreis, gemeindeschluessel),
         daten_stand = if_else(is.na(daten_stand), as_datetime(date), daten_stand)) %>% 
  select(-kreis, -X1, -faelle_covid_aktuell_im_bundesland, -date)
```


```{r eval=FALSE}
data_clean %>% 
  naniar::vis_miss(warn_large_data = FALSE) +
  theme_light(base_size = )


```


```{r}
g1 <- data_clean %>% 
  select(bundesland, daten_stand, betten_belegt, betten_frei) %>% 
  mutate(occupancy = betten_belegt/(betten_frei+betten_belegt)*100,
         occupancy = round(occupancy, 1)) %>% 
  group_by(daten_stand) %>% 
  summarise(avg_occupancy = mean(occupancy)) %>% 
  ggplot(aes(daten_stand, avg_occupancy, color = "black")) +
  geom_line(size = 1.2) +
  labs(title = "Average bed occupacy of ICU Units",
       subtitle = paste0("Data source @rki, Date: ", heute),
       y = "Average ICU bed occupacy in %",
       x = "Date") +
  ggsci::scale_color_lancet(guide = "none")

g2 <- data_clean %>% 
  select(bundesland, daten_stand, betten_belegt, betten_frei) %>% 
  mutate(beds_available = betten_frei+betten_belegt) %>% 
  group_by(daten_stand) %>% 
  summarise(total_bed = sum(beds_available)) %>% 
  ggplot(aes(daten_stand, total_bed, color = "black")) +
  geom_line(size = 1.2) +
  ggsci::scale_color_lancet(guide = "none") +
  labs(title = "Total bed capacity of ICU Units",
       subtitle = paste0("Data source @rki, Date: ", heute),
       y = "Total ICU bed capacity",
       x = "Date")

capa <- g1 / g2
save(capa, file = "figs/capa.RData")
capa
```


## Percentage of COVID cases occupied ICU beds

```{r fig.height=8}
map_de <- readRDS("data/gadm36_DEU_2_sp.rds")
kreis_bl <- map_de@data %>% as_tibble() %>% 
  select(gemeindeschluessel = CC_2, bundesland = NAME_1) %>% 
  distinct() %>% 
  na.omit() %>% 
  bind_rows(
    tibble(
      gemeindeschluessel = "03159",
      bundesland = "Niedersachsen"
    )
  )

covid_beds <- data_clean %>% 
  select(gemeindeschluessel, daten_stand, betten_belegt, betten_frei, faelle_covid_aktuell, faelle_covid_aktuell_beatmet) %>% 
  mutate(betten_total = betten_belegt+betten_frei) %>% 
  select(-betten_belegt, -betten_frei) %>% 
  filter(!is.na(faelle_covid_aktuell)) %>% 
  left_join(
    kreis_bl
  ) %>% 
  select(gemeindeschluessel, bundesland, daten_stand, faelle_covid_aktuell, faelle_covid_aktuell_beatmet, betten_total) 

saveRDS(covid_beds, "data/covid_beds.rds")

covid_beds_perc <- covid_beds %>% 
  group_by(bundesland, daten_stand) %>% 
  summarise(bl_covid_n = sum(faelle_covid_aktuell, na.rm = TRUE),
            bl_covid_vent_n = sum(faelle_covid_aktuell_beatmet, na.rm = TRUE),
            bl_total_beds_n = sum(betten_total, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(covid_perc = round(bl_covid_n/bl_total_beds_n*100,1))

g_beds <- covid_beds_perc %>% 
  ggplot(aes(daten_stand, covid_perc, group = bundesland, color = "black")) +
  geom_line(size = 1, alpha = 0.4) +
  geom_line(
    data = covid_beds_perc %>% 
      mutate(daten_stand = floor_date(daten_stand, "week")) %>% 
      group_by(daten_stand, bundesland) %>% 
      summarise(covid_perc = median(covid_perc)),
    aes(color = "green")
  ) +
  ggsci::scale_color_lancet(guide = "none") +
  facet_wrap(~bundesland, nrow = 4) +
  labs(title = "Weekly percentage of COVID cases occupied ICU beds",
       subtitle = paste0("Data source @rki, Date: ", heute),
       x = "Date",
       y = "COVID cases in %") +
  theme(strip.background = element_rect(fill = "#152238"),
        strip.text = element_text(colour = 'white', face = "bold"),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))

save(g_beds, file = "figs/beds.RData")
g_beds

```



